services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: library_user
      POSTGRES_PASSWORD: library_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U library_user -d library -h 127.0.0.1"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"  

  api:
    build:
      context: ./api
    env_file:
      - ./api/.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  web:
    build:
      context: ./web
      args:
        VITE_API_BASE: "http://localhost:8000"
    depends_on:
      - api
    ports:
      - "5173:80"

volumes:
  pgdata:
