apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: library
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_USER
              value: library_user
            - name: POSTGRES_PASSWORD
              value: library_pass
            - name: POSTGRES_DB
              value: library
          ports:
            - containerPort: 5432
