name: Build & Push Docker Images

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_NAMESPACE: ${{ secrets.DOCKERHUB_USERNAME }}

    strategy:
      matrix:
        include:
          - name: backend
            context: api
            dockerfile: api/Dockerfile
            image_name: library-app
            build_args: |
              DB_HOST=db
              DB_PORT=5432
              DB_NAME=library
              DB_USER=library_user
              DB_PASSWORD=library_pass
              APP_PORT=8000
              ENVIRONMENT=local
          - name: frontend
            context: web
            dockerfile: web/Dockerfile
            image_name: library-web
            build_args: |
              VITE_API_BASE=http://localhost:8000

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_NAMESPACE }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Generate tags/labels
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_NAMESPACE }}/${{ matrix.image_name }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ matrix.build_args }}
          platforms: linux/amd64
